# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{bdb}
  s.version = "0.2.6"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = [%q{Justin Balthrop}, %q{Denis Knauf}, %q{Ash Moran}]
  s.date = %q{2011-08-24}
  s.description = %q{Advanced Ruby Berkeley DB library.}
  s.email = [%q{code@justinbalthrop.com}, %q{Denis.Knauf@gmail.com}, %q{ash.moran@patchspace.co.uk}]
  s.extensions = [%q{ext/extconf.rb}]
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.files = [
    "AUTHORS",
    "README.md",
    "VERSION",
    "ext/bdb.c",
    "ext/bdb.h",
    "lib/bdb/base.rb",
    "lib/bdb/database.rb",
    "lib/bdb/environment.rb",
    "lib/bdb/partitioned_database.rb",
    "lib/bdb/replication.rb",
    "lib/bdb/result_set.rb",
    "test/benchmark.rb",
    "test/cursor_test.rb",
    "test/database_test.rb",
    "test/database_test_helper.rb",
    "test/db_test.rb",
    "test/deadlock_test.rb",
    "test/env_test.rb",
    "test/replication_test.rb",
    "test/stat_test.rb",
    "test/test_helper.rb",
    "test/txn_test.rb"
  ]
  s.homepage = %q{http://github.com/ninjudd/bdb}
  s.require_paths = [%q{ext}, %q{lib}]
  s.rubygems_version = %q{1.8.9}
  s.summary = %q{Ruby Berkeley DB}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

